### PR TITLE
Permit multiple data subscriptions per original topic

### LINKED ISSUE #126: block sent listener is not called for every block sent
I added [`TestDataSentEvents`](https://github.com/filecoin-project/go-data-transfer/blob/f1eb52e23c8efb76f4ce412e08333a59574ed38b/impl/integration_test.go#L238) as an integration test in go-data-transfer to watch for events emitted. It seems that `gsBlockSentHook` is not called every time that a block is sent (whereas `gsIncomingBlockHook` *is* called every time a block is received). `gsBlockSentHook` is [registered with graphsync using `RegisterBlockSentListener`](https://github.com/filecoin-project/go-data-transfer/blob/f1eb52e23c8efb76f4ce412e08333a59574ed38b/transport/graphsync/graphsync.go#L297).

The full output from the test is below. Note the output for the last two lines:
```
prov [Completed] CleanupComplete: qd 0, rcvd 20439, sent 0, total: 0
clnt [Completed] CleanupComplete: qd 20439, rcvd 0, sent 14295, total: 0
```
On the provider graphsync emitted "receive" events for `20439` bytes.
On the client graphsync emitted "queue" events for `20439` bytes, but only emitted "sent" events for `14295` bytes.

Full output:
```
clnt [Requested] Open: qd 0, rcvd 0, sent 0, total: 0
prov [Requested] Open: qd 0, rcvd 0, sent 0, total: 0
prov [Ongoing] Accept: qd 0, rcvd 0, sent 0, total: 0
clnt [Ongoing] Accept: qd 0, rcvd 0, sent 0, total: 0
clnt [Ongoing] ResumeResponder: qd 0, rcvd 0, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 966, rcvd 0, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 1990, rcvd 0, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 3014, rcvd 0, sent 0, total: 0
clnt [Ongoing] DataSent: qd 3014, rcvd 0, sent 966, total: 0
clnt [Ongoing] DataQueued: qd 4038, rcvd 0, sent 966, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 966, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 5062, rcvd 0, sent 966, total: 0
clnt [Ongoing] DataSent: qd 5062, rcvd 0, sent 1990, total: 0
clnt [Ongoing] DataQueued: qd 6086, rcvd 0, sent 1990, total: 0
clnt [Ongoing] DataQueued: qd 7110, rcvd 0, sent 1990, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 1990, sent 0, total: 0
clnt [Ongoing] DataSent: qd 7110, rcvd 0, sent 3014, total: 0
clnt [Ongoing] DataQueued: qd 8134, rcvd 0, sent 3014, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 3014, sent 0, total: 0
clnt [Ongoing] DataSent: qd 8134, rcvd 0, sent 4038, total: 0
clnt [Ongoing] DataQueued: qd 9158, rcvd 0, sent 4038, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 4038, sent 0, total: 0
clnt [Ongoing] DataSent: qd 9158, rcvd 0, sent 5062, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 5062, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 10182, rcvd 0, sent 5062, total: 0
clnt [Ongoing] DataSent: qd 10182, rcvd 0, sent 6086, total: 0
clnt [Ongoing] DataQueued: qd 11206, rcvd 0, sent 6086, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 6086, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 12230, rcvd 0, sent 6086, total: 0
clnt [Ongoing] DataSent: qd 12230, rcvd 0, sent 7110, total: 0
clnt [Ongoing] DataQueued: qd 13254, rcvd 0, sent 7110, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 7110, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 14278, rcvd 0, sent 7110, total: 0
clnt [Ongoing] DataSent: qd 14278, rcvd 0, sent 8134, total: 0
clnt [Ongoing] DataQueued: qd 15302, rcvd 0, sent 8134, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 8134, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 16326, rcvd 0, sent 8134, total: 0
clnt [Ongoing] DataSent: qd 16326, rcvd 0, sent 9158, total: 0
clnt [Ongoing] DataQueued: qd 17350, rcvd 0, sent 9158, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 9158, sent 0, total: 0
clnt [Ongoing] DataSent: qd 17350, rcvd 0, sent 10182, total: 0
clnt [Ongoing] DataQueued: qd 18374, rcvd 0, sent 10182, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 10182, sent 0, total: 0
clnt [Ongoing] DataQueued: qd 19398, rcvd 0, sent 10182, total: 0
clnt [Ongoing] DataSent: qd 19398, rcvd 0, sent 11206, total: 0
clnt [Ongoing] DataQueued: qd 20422, rcvd 0, sent 11206, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 11206, sent 0, total: 0
clnt [Ongoing] DataSent: qd 20422, rcvd 0, sent 12230, total: 0
clnt [Ongoing] DataQueued: qd 20439, rcvd 0, sent 12230, total: 0
clnt [Ongoing] DataSent: qd 20439, rcvd 0, sent 13254, total: 0
clnt [Ongoing] DataSent: qd 20439, rcvd 0, sent 14278, total: 0
clnt [Ongoing] DataSent: qd 20439, rcvd 0, sent 14295, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 12230, sent 0, total: 0
clnt [TransferFinished] FinishTransfer: qd 20439, rcvd 0, sent 14295, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 13254, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 14278, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 15302, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 16326, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 17350, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 18374, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 19398, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 20422, sent 0, total: 0
prov [Ongoing] DataReceived: qd 0, rcvd 20439, sent 0, total: 0
clnt [Completing] ResponderCompletes: qd 20439, rcvd 0, sent 14295, total: 0
prov [Completing] Complete: qd 0, rcvd 20439, sent 0, total: 0
prov [Completed] CleanupComplete: qd 0, rcvd 20439, sent 0, total: 0
clnt [Completed] CleanupComplete: qd 20439, rcvd 0, sent 14295, total: 0

    integration_test.go:342: 
        	Error Trace:	integration_test.go:342
        	Error:      	Not equal: 
        	            	expected: []uint64{0x3c6, 0x7c6, 0xbc6, 0xfc6, 0x13c6, 0x17c6, 0x1bc6, 0x1fc6, 0x23c6, 0x27c6, 0x2bc6, 0x2fc6, 0x33c6, 0x37c6, 0x3bc6, 0x3fc6, 0x43c6, 0x47c6, 0x4bc6, 0x4fc6, 0x4fd7}
        	            	actual  : []uint64{0xbc6, 0x13c6, 0x1bc6, 0x1fc6, 0x23c6, 0x27c6, 0x2fc6, 0x37c6, 0x3fc6, 0x43c6, 0x4bc6, 0x4fc6, 0x4fd7, 0x4fd7, 0x4fd7}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,8 +1,4 @@
        	            	-([]uint64) (len=21) {
        	            	- (uint64) 966,
        	            	- (uint64) 1990,
        	            	+([]uint64) (len=15) {
        	            	  (uint64) 3014,
        	            	- (uint64) 4038,
        	            	  (uint64) 5062,
        	            	- (uint64) 6086,
        	            	  (uint64) 7110,
        	            	@@ -11,12 +7,10 @@
        	            	  (uint64) 10182,
        	            	- (uint64) 11206,
        	            	  (uint64) 12230,
        	            	- (uint64) 13254,
        	            	  (uint64) 14278,
        	            	- (uint64) 15302,
        	            	  (uint64) 16326,
        	            	  (uint64) 17350,
        	            	- (uint64) 18374,
        	            	  (uint64) 19398,
        	            	  (uint64) 20422,
        	            	+ (uint64) 20439,
        	            	+ (uint64) 20439,
        	            	  (uint64) 20439
        	Test:       	TestDataSentEvents
--- FAIL: TestDataSentEvents (0.01s)
FAIL

Debugger finished with exit code 0
```

### PR DESCRIPTION
**Pull request by acruikshank**
closes #126

### Motivation

When we add new data topics, we would map the block topic to a response topic on the subscriber. It is possible for multiple blocks to go out in one response, however, so the subscriptions would overwrite each other. 

This PR first refactors the subscription system to remove the concept of mapping and replace it with the concept of data topics. It then modifies the subscriber to permit multiple data subscribers per topic and ensure that each of these data subscribers is notified when a topic event is published.

### Proposed Changes

1. Eliminate the `MappableSubscriber` interface because there only needs to be one implementation.
2. Introduce `TopicData` to slightly distinguish data subscriptions from the original topic subscription. This replaces the mappable topic.
3. Rename `notifications.SubscribeOn` to `notifications.SubscribeWithData` for clarity.
4. Rename `mappable.go` to `data_subscriber.go` and rename `mappableSubscriber` to `TopicDataSubscriber`.
5. Replace `Notifee`'s `topic` with a `data` field of type `TopicData`.
6. Replace `mappableSubscriber`'s `idMap` with `TopicDataSubscriber`'s `data` which is now a map of topics to multiple `TopicData`s.
7. `DataSubscriber`'s `OnNext` and and `OnClose` now call the corresponding methods on the internal subscriber once for each `TopicData` mapped to the original topic. This fixes #126.
8. Add a test that a listener registered with `RegisterBlockSentListener` will get called once for every block actually sent (i.e. that #126 has been fixed). This test failed before the last two changes.

cc @dirkmc

### CODE REVIEW

File: notifications/notifications_test.go [hunk 1]
```diff
@@ -12,10 +12,10 @@ import (
 func TestSubscribeOn(t *testing.T) {
```
Comment (dirkmc) [inline notifications/notifications_test.go:12]:
```suggestion
func TestSubscribeWithData(t *testing.T) {
```

**Review by dirkmc — APPROVED** [review]
Looks great! 👍

**Comment by dirkmc** [comment]
Confirmed that this fixes the go-data-transfer test [`TestDataSentEvents`](https://github.com/filecoin-project/go-data-transfer/blob/f1eb52e23c8efb76f4ce412e08333a59574ed38b/impl/integration_test.go#L238)
